-- MySQL Script generated by MySQL Workbench
-- Fri Jul  2 11:02:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
drop database if EXISTS `project` ;
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 ;
USE `project` ;
-- -----------------------------------------------------
-- Table `project`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`member` (
  `sn` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NOT NULL,
  `gender` ENUM('남자', '여자', '기타') NOT NULL,
  `friendcount` INT NULL DEFAULT 0,
  `hint` VARCHAR(45) NULL,
  `answer` VARCHAR(45) NULL,
  `rdate` TIMESTAMP NULL DEFAULT current_timestamp,
  `state` ENUM('승인중', '회원') NOT NULL DEFAULT '승인중',
  PRIMARY KEY (`sn`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`friend` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `sn` INT NOT NULL,
  `friend_sn` INT NOT NULL,
  `state` ENUM('friend', 'block') NULL,
  INDEX `fk_friend_member1_idx` (`sn` ASC) ,
  INDEX `fk_friend_member2_idx` (`friend_sn` ASC) ,
  PRIMARY KEY (`no`),
  CONSTRAINT `fk_friend_member1`
    FOREIGN KEY (`sn`)
    REFERENCES `project`.`member` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_member2`
    FOREIGN KEY (`friend_sn`)
    REFERENCES `project`.`member` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`state` (
  `sn` INT NOT NULL,
  `state` ENUM('접속중', '로그오프', '기타용무중') NULL,
  `logintime` DATE NULL,
  `logouttime` DATE NULL,
  `viewtime` TIMESTAMP NULL DEFAULT current_timestamp,
  `lastviewtime` DATE NULL,
  PRIMARY KEY (`sn`),
  CONSTRAINT `fk_state_member1`
    FOREIGN KEY (`sn`)
    REFERENCES `project`.`member` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`board` (
  `sn` INT NOT NULL AUTO_INCREMENT,
  `writer` INT NOT NULL,
  `contents` VARCHAR(250) NOT NULL,
  `wdate` TIMESTAMP NULL DEFAULT current_timestamp,
  `state` ENUM('전체', '친구') NULL DEFAULT '전체',
  PRIMARY KEY (`sn`),
  INDEX `fk_board_member1_idx` (`writer` ASC) ,
  CONSTRAINT `fk_board_member1`
    FOREIGN KEY (`writer`)
    REFERENCES `project`.`member` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`comment` (
  `sn` INT NOT NULL AUTO_INCREMENT,
  `board_sn` INT NOT NULL,
  `writer` INT NOT NULL,
  `contents` VARCHAR(45) NOT NULL,
  INDEX `fk_comment_board1_idx` (`board_sn` ASC) ,
  PRIMARY KEY (`sn`),
  INDEX `fk_comment_member1_idx` (`writer` ASC) ,
  CONSTRAINT `fk_comment_board1`
    FOREIGN KEY (`board_sn`)
    REFERENCES `project`.`board` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_member1`
    FOREIGN KEY (`writer`)
    REFERENCES `project`.`member` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`attach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`attach` (
  `sn` INT NOT NULL AUTO_INCREMENT,
  `board_sn` INT NOT NULL,
  `filename` VARCHAR(45) NULL,
  `filesize` INT NULL,
  INDEX `fk_attach_board1_idx` (`board_sn` ASC) ,
  PRIMARY KEY (`sn`),
  CONSTRAINT `fk_attach_board1`
    FOREIGN KEY (`board_sn`)
    REFERENCES `project`.`board` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`hashtag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`hashtag` (
  `sn` INT NOT NULL AUTO_INCREMENT,
  `board_sn` INT NOT NULL,
  `hashName` VARCHAR(45) NULL,
  INDEX `fk_table1_board1_idx` (`board_sn` ASC) ,
  PRIMARY KEY (`sn`),
  CONSTRAINT `fk_table1_board1`
    FOREIGN KEY (`board_sn`)
    REFERENCES `project`.`board` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`commentLike`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`commentLike` (
  `comment_sn` INT NOT NULL,
  `writer` INT NOT NULL,
  `like` INT NULL,
  `report` INT NULL,
  INDEX `fk_commentLike_comment1_idx` (`comment_sn` ASC) ,
  PRIMARY KEY (`comment_sn`, `writer`),
  INDEX `fk_commentLike_member1_idx` (`writer` ASC) ,
  CONSTRAINT `fk_commentLike_comment1`
    FOREIGN KEY (`comment_sn`)
    REFERENCES `project`.`comment` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentLike_member1`
    FOREIGN KEY (`writer`)
    REFERENCES `project`.`member` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `project`.`memberpost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`memberpost` (
  `sn` INT NOT NULL,
  `post` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `addresstail` VARCHAR(45) NULL,
  `birthplace` VARCHAR(45) NULL,
  `jobaddress` VARCHAR(45) NULL,
  PRIMARY KEY (`sn`),
  CONSTRAINT `fk_memberpost_member1`
    FOREIGN KEY (`sn`)
    REFERENCES `project`.`member` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`memberprofile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`memberprofile` (
  `sn` INT NOT NULL,
  `profile` BLOB NULL,
  `backprofile` BLOB NULL,
  PRIMARY KEY (`sn`),
  CONSTRAINT `fk_memberprofile_member1`
    FOREIGN KEY (`sn`)
    REFERENCES `project`.`member` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`memberschool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`memberschool` (
  `sn` INT NOT NULL,
  `row` VARCHAR(45) NULL,
  `middle` VARCHAR(45) NULL,
  `high` VARCHAR(45) NULL,
  `university` VARCHAR(45) NULL,
  PRIMARY KEY (`sn`),
  CONSTRAINT `fk_memberschool_member1`
    FOREIGN KEY (`sn`)
    REFERENCES `project`.`member` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`chatroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`chatroom` (
  `sn` INT NOT NULL AUTO_INCREMENT,
  `roomname` VARCHAR(45) NULL,
  PRIMARY KEY (`sn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`chat` (
  `chatroom_sn` INT NOT NULL,
  `member_sn` INT NOT NULL,
  INDEX `fk_chat_member1_idx` (`member_sn` ASC) ,
  INDEX `fk_chat_chatroom1_idx` (`chatroom_sn` ASC) ,
  PRIMARY KEY (`chatroom_sn`, `member_sn`),
  CONSTRAINT `fk_chat_member1`
    FOREIGN KEY (`member_sn`)
    REFERENCES `project`.`member` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_chatroom1`
    FOREIGN KEY (`chatroom_sn`)
    REFERENCES `project`.`chatroom` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`chating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`chating` (
  `sn` INT NOT NULL AUTO_INCREMENT,
  `chatroom_sn` INT NOT NULL,
  `writer` INT NOT NULL,
  `contents` VARCHAR(45) NULL,
  `rdate` DATE NULL,
  PRIMARY KEY (`sn`, `chatroom_sn`),
  INDEX `fk_chating_chat1_idx` (`chatroom_sn` ASC, `writer` ASC) ,
  CONSTRAINT `fk_chating_chat1`
    FOREIGN KEY (`chatroom_sn` , `writer`)
    REFERENCES `project`.`chat` (`chatroom_sn` , `member_sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`boardlike`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`boardlike` (
  `board_sn` INT NOT NULL,
  `writer` INT NOT NULL,
  `like` INT NULL,
  `report` INT NULL,
  INDEX `fk_boardlike_board1_idx` (`board_sn` ASC) ,
  INDEX `fk_boardlike_member1_idx` (`writer` ASC) ,
  PRIMARY KEY (`writer`, `board_sn`),
  CONSTRAINT `fk_boardlike_board1`
    FOREIGN KEY (`board_sn`)
    REFERENCES `project`.`board` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boardlike_member1`
    FOREIGN KEY (`writer`)
    REFERENCES `project`.`member` (`sn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into member(id,password,name,age,gender,state) values ('sung','1234','성상현','1992-07-06','남자','회원');
insert into member(id,password,name,age,gender,state) values ('woong','1234','이영웅','1996-11-24','남자','회원');
insert into member(id,password,name,age,gender,state) values ('hak','1234','이학명','1998-04-29','남자','회원');
select year(now())-year(age)+1 as age from member where sn=1;
