/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-08-26 11:59:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.lec206.acebook.vo_member.Member;

public final class personPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1624095629010L));
    _jspx_dependants.put("jar:file:/C:/Users/cholc/Desktop/hm/project_sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/acebookXMLVer2/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/cholc/Desktop/hm/project_sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/acebookXMLVer2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.lec206.acebook.vo_member.Member");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
HttpSession session= request.getSession(false); 
      out.write('\r');
      out.write('\n');
Member member = (Member)request.getAttribute("member"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- css , font, jq  -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{background-color:#F0F2F5;}\r\n");
      out.write("#box{width:55%; margin: 0 auto;}\r\n");
      out.write(".divbox{margin-left:0px; width:70%; height:auto;  background-color:white; margin-bottom: 2%; border: 1px solid #E2E4E7; border-radius: 5px;}\r\n");
      out.write(".divcotents{height:150px; overflow:auto; padding-left:10px; padding-right:10px;}\r\n");
      out.write(".profile{border-radius: 30px;}\r\n");
      out.write(".profile1{border-radius: 100%;}\r\n");
      out.write(".pointer{cursor: pointer;}\r\n");
      out.write(".contentstop{padding-top: 10px;padding-left: 10px; display:flex;}\r\n");
      out.write(".contentsname{padding-top: 10px;}\r\n");
      out.write(".boardsave{margin-left:0px; display:flex; width:69%; height:7%;  background-color:white; margin-bottom: 2%; padding-top:1%; padding-left:1%;  border: 1px solid #E2E4E7; border-radius: 5px;}\r\n");
      out.write(".rboardsave{width:88%; height:20%; margin: 0 auto; background-color:#F0F2F5; margin-left: 1%; margin-top: 1%; margin-bottom: 2%; padding:1%;   border: 1px solid #E2E4E7; border-radius: 15px;}\r\n");
      out.write(".conselect{right:1%; height:10%; margin-top:1%;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#center{display: flex; flex-wrap:nowrap; width: 100%; padding-top:255px;}\r\n");
      out.write("#left{\r\n");
      out.write("padding : 10;\r\n");
      out.write("  height: 800px;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  order: 1;\r\n");
      out.write("  margin-right: 1px;\r\n");
      out.write("  display:flex;\r\n");
      out.write("}\r\n");
      out.write("#right{\r\n");
      out.write("padding : 10;\r\n");
      out.write("  height: 800px;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  order: 2;\r\n");
      out.write("  margin-left: 1px;\r\n");
      out.write("}\r\n");
      out.write(".contentleft{width:70%; margin-left:43%; display:flex;}\r\n");
      out.write(".ifriendstate{width:100%; border-radius: 5px; border: 1px solid #E2E4E7;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".top{width:50%; padding-left: 30%;}\r\n");
      out.write(".backprofile{left:30%; width:45%; height:200px; position:absolute; border-radius: 20px;}\r\n");
      out.write(".myprofile{left:48%; width:10%; height:10%; top:170px; position:absolute; border: 5px solid white;}\r\n");
      out.write(".topback{height: 255px; background: linear-gradient(to bottom, gray, white); }\r\n");
      out.write(".friendbt{left:63%; top:200px;  position:absolute;}\r\n");
      out.write("\r\n");
      out.write(".like{background-color: blue; font-weight:bold; color:white;}\r\n");
      out.write("#wrap {position:fixed; width:500px; height:300px; left:40%; top:40%; background-color:white;border: 1px solid black;}\r\n");
      out.write("#sharing {background-color:white;border: 1px solid black;}\r\n");
      out.write("/*친구추가 및 차단 css */ \r\n");
      out.write(".btn { display:block; width:150px; height:30px; line-height:40px; border:1px #3399dd solid;; margin:15px auto; background-color:#66aaff; text-align:center; cursor: pointer; color:#333; transition:all 0.9s, color 0.3; } .btn:hover{color:#fff;}\r\n");
      out.write(".hover1:hover{ box-shadow:200px 0 0 0 rgba(0,0,0,0.5) inset; }\r\n");
      out.write(".hover2:hover{ box-shadow:200px 0 0 0 rgba(0,0,0,0.5) inset; }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<title>");
      out.print(member.getName()+"페이지" );
      out.write("</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- startcon -->\r\n");
      out.write("\r\n");
if(member.getSn() == (Integer)session.getAttribute("sn")) {
      out.write("\r\n");
      out.write("<div class=\"top\">\r\n");
      out.write("<div><img class=\"pointer backprofile\" onclick=\"open_layer(5,0)\" src =\"/board/attach/");
      out.print(member.getBackprofile());
      out.write("\" id=\"myimg\"/></div>\r\n");
      out.write("<div><img class=\"pointer profile1 myprofile\" onclick=\"open_layer(2,0)\" src =\"/board/attach/");
      out.print(member.getProfile());
      out.write("\" id=\"myimg\" height=\"100\" width=\"100\"/></div>\r\n");
      out.write("</div>\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
if(member.getSn() != (Integer)session.getAttribute("sn")) {
      out.write("\r\n");
      out.write("<div class=\"top\">\r\n");
      out.write("<div><img class=\"backprofile\" src =\"/board/attach/");
      out.print(member.getBackprofile());
      out.write("\" id=\"myimg\" height=\"100\" width=\"100\"/></div>\r\n");
      out.write("<div><img class=\"profile1 myprofile\" src =\"/board/attach/");
      out.print(member.getProfile());
      out.write("\" id=\"myimg\" height=\"100\" width=\"100\"/></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 영웅이 개인페이지 코드{ -->\r\n");
      out.write("\r\n");
      out.write("<!-- 영웅이 개인페이지 코드 -->\r\n");
      out.write("\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"topback\">\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"center\" class=\"contents\">\r\n");
      out.write("<div id=\"left\">\r\n");
      out.write("<div class=\"contentleft\" ><iframe class=\"ifriendstate\" src=\"/personstate/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.sn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"lframe\" onload=\"Height();\" frameborder=\"0\" style=\"overflow-x:hidden; overflow:auto; width:100%; height:26%;\"></iframe></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"right\">\r\n");
      out.write("\r\n");
if(member.getSn() != (Integer)session.getAttribute("sn")) {
      out.write("\r\n");
      out.write("<input type=\"button\" onclick=\"open_layer(8,0)\" value=\"채팅\">\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
if(member.getSn() == (Integer)session.getAttribute("sn")) {
      out.write("\r\n");
      out.write("<div class=\"boardsave\" ><img class=\"profile pointer\" onclick=\"person(");
      out.print(session.getAttribute("sn"));
      out.write(")\" src =\"/board/attach/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.profile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"myimg\" height=\"40\" width=\"40\"/>\r\n");
      out.write("<div class=\"rboardsave pointer\" onclick=\"open_layer(1,0)\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님, 오늘은 무슨 생각을 하고 계신가요?</div>\r\n");
      out.write("</div>\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"divpop\" style=\"position:fixed; top:100; left:100px; z-index:300; visibility:hidden;\">\r\n");
      out.write("<table cellpadding=\"5\" cellspacing=\"0\" bgcolor=\"#FFFFFF\" border=\"5\" bordercolor=\"#424242\">\r\n");
      out.write("<tr><td>\r\n");
      out.write("<iframe name=\"i_frame\" src=\"#\" width=\"450\" height=\"350\" marginwidth=\"0\" marginheight=\"0\" frameborder=\"no\" scrolling=\"auto\"></iframe>\r\n");
      out.write("</td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"right\" height=\"10\" bgcolor=\"#424242\">\r\n");
      out.write("<button type=\"button\" id=\"closebt\" onclick=\"close_layer();\">닫기</button>\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table></div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"list\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"wrap\" style=\"visibility:hidden;\" width=\"400\" height=\"100\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- endcon -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("/* 영웅이코드{  */\r\n");
      out.write("function 친구신청(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t  url: '/request/'+");
      out.print(member.getSn());
      out.write(",\r\n");
      out.write("\t\t  success: function (data) {\r\n");
      out.write("\t\t    console.log(data),\r\n");
      out.write("\t\t    alert(\"신청완료\"),\r\n");
      out.write("\t\t    window.location.reload()\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function 친구수락(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t  url: '/accept/'+");
      out.print(member.getSn());
      out.write(",\r\n");
      out.write("\t\t  success: function (data) {\r\n");
      out.write("\t\t    console.log(data),\r\n");
      out.write("\t\t    alert(\"친구수락완료\"),\r\n");
      out.write("\t\t    window.location.reload()\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function 친구차단(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t  url: '/request/'+");
      out.print(member.getSn());
      out.write(",\r\n");
      out.write("\t\t  success: function (data) {\r\n");
      out.write("\t\t    console.log(data),\r\n");
      out.write("\t\t    alert(\"신청완료\"),\r\n");
      out.write("\t\t    window.location.reload()\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 영웅이코드} */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function 알림(sn,board){\r\n");
      out.write("\tvar content = \"\";\r\n");
      out.write("\tif(sn==1){content = \"수정하시겠습니까?\";}\r\n");
      out.write("\tif(sn==2){content = \"삭제하시겠습니까?\";}\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.all['wrap'].style.visibility = \"visible\";\r\n");
      out.write("\t$(\"#wrap\").empty();\r\n");
      out.write("\t$(\"#wrap\").prepend(content);\r\n");
      out.write("\t$(\"#wrap\").append(\"<button type=\\\"button\\\" onclick=\\\"게시물상태(\"+sn+\",\"+board+\")\\\">확인</button>\");\r\n");
      out.write("\t$(\"#wrap\").append(\"<button type=\\\"button\\\" onclick=\\\"closelayer()\\\">취소</button>\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function 게시물상태(sn,board){\r\n");
      out.write("\tif(sn==1){open_layer(4,board);closelayer();}\r\n");
      out.write("\tif(sn==2){게시물삭제(board);}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function closelayer(){\r\n");
      out.write("\tdocument.all['wrap'].style.visibility = \"hidden\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function open_layer(key,board){\r\n");
      out.write("\tdocument.all['closebt'].style.visibility = \"visible\";\r\n");
      out.write("\tif(key==1){ var page = \"/board\";}\r\n");
      out.write("\tif(key==2){ var page =\"/profile\";}\r\n");
      out.write("\tif(key==3){ var page =\"/eachboard/\"+board;}\r\n");
      out.write("\tif(key==4){ var page =\"/modifyboard/\"+board;}\r\n");
      out.write("\tif(key==5){ var page =\"/backprofile\";}\r\n");
      out.write("\tif(key==7){ var page = \"/likepeople/\"+board;}\r\n");
      out.write("\tif(key==8){ var page = \"/chatroom/\"+");
      out.print(session.getAttribute("sn"));
      out.write("+\"/\"+");
      out.print(member.getSn());
      out.write(";\r\n");
      out.write("\t\t\t\tdocument.all['closebt'].style.visibility = \"hidden\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.all['divpop'].style.visibility = \"visible\";\r\n");
      out.write("\tdocument.i_frame.location.replace(page);\r\n");
      out.write("\t}\r\n");
      out.write("function close_layer(){\r\n");
      out.write("\tdocument.all['closebt'].style.visibility = \"hidden\";\r\n");
      out.write("\t document.all['divpop'].style.visibility = \"hidden\";\r\n");
      out.write("\t}\r\n");
      out.write("function init() {\r\n");
      out.write("\t  var getval = $('tag name[name=i_frame]').contents().find('#close').val();\r\n");
      out.write("\t  alert(getval);\r\n");
      out.write("\t }\r\n");
      out.write("\t\r\n");
      out.write("window.onload = function (){\r\n");
      out.write("\t\r\n");
      out.write("\t게시물로드(3);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var size =-3;\r\n");
      out.write("function 게시물로드(plus){\r\n");
      out.write("\tsize = size +parseInt(plus);\r\n");
      out.write("\t\tvar value={size:size};\r\n");
      out.write("\t\t $.ajax({url: \"/profile/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("\t            success : function(data) {\r\n");
      out.write("                \t$(\"#list\").append('<div id=\"box\">');\r\n");
      out.write("                \t$.each(data,function(index, item){\r\n");
      out.write("                \t\t$(\"#list\").append('<div class=\"divbox\" id=\\\"boxnum'+item.sn+'\\\">'\r\n");
      out.write("                \t\t\t\t+\"<div class=\\\"contentstop\\\" style=\\\"list-style: none;\\\"><a class=\\\"pointer\\\" onclick=\\\"person(\"+item.writer.sn+\")\\\"><img class=\\\"profile\\\" src =\\\"/board/attach/\"+item.writer.profile+\"\\\" id=\\\"myimg\\\" height=\\\"40\\\" width=\\\"40\\\"/></a>\"+\r\n");
      out.write("                \t\t\t\t\"<a class=\\\"pointer contentsname\\\" onclick = \\\"person(\"+item.writer.sn+\")\\\">&nbsp<b>\"+\r\n");
      out.write("                \t\t\t\titem.writer.name+\"</b></a>\"+\r\n");
      out.write("                \t\t\t\t\"&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\"+\r\n");
      out.write("\t                \t\t\t\"<select class=\\\"conselect\\\" onchange=\\\"알림(this.value,\"+item.sn+\")\\\">\\r\\n\" + \r\n");
      out.write("\t                \t\t\t\"<option value=\\\"none\\\" disabled selected> 선택 </option>\\r\\n\" + \r\n");
      out.write("\t                \t\t\t\"<option value=\\\"1\\\">수정</option>\\r\\n\" + \r\n");
      out.write("\t                \t\t\t\"<option value=\\\"2\\\">삭제</option>\\r\\n\" + \r\n");
      out.write("\t                \t\t\t\"</select></div>\"\r\n");
      out.write("\t                \t\t\t+\"<div class=\\\"divcotents\\\">내용\"+item.contents+\"<div id=photo\"+item.sn+\"></div>\"\r\n");
      out.write("\t                \t\t\t+\" 날짜\"+item.wdate\r\n");
      out.write("\t                \t\t\t+\"<div id=\\\"sharing\"+item.sn+\"\\\"></div>\"\r\n");
      out.write("\t                \t\t\t+\"박스번호: box\"+(size+index)+\" 게시물번호:\"+item.sn+\"</div><div id=box\"+item.sn+\">\"+\"</div>\"+\"<div id=like\"+item.sn+\">\"+\"</div>\"+\"<input type=\\\"button\\\" onclick=\\\"댓글(\"+item.sn+\",\"+");
      out.print(member.getProfile());
      out.write("+\",0)\\\" id=\\\"comments\"+item.sn+\"\\\" value=\\\"댓글\\\" /><div id=comment\"+item.sn+\" class=\\\"comment\\\">\"+\"</div><div id=photo\"+item.sn+\">\"+\"</div>\"+'</div>');\r\n");
      out.write("                \t\t좋아요갯수(item.sn);\r\n");
      out.write("                \t\t좋아요여부(item.sn,");
      out.print(session.getAttribute("sn"));
      out.write(");\r\n");
      out.write("                  \t\t사진출력(item.sn);\r\n");
      out.write("                \t\tif(item.state==\"공유\"){공유글(item.sn);}\r\n");
      out.write("                \t});\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                \t$(\"#list\").append('</div>');\r\n");
      out.write("\t            },\r\n");
      out.write("\t\t    \terror:function(result){\r\n");
      out.write("\t\t\t     alert(\"Error404\"+result); \r\n");
      out.write("\t\t\t    },\r\n");
      out.write("\t         type:\"POST\",\r\n");
      out.write("\t         data :value,\r\n");
      out.write("\t        });}\r\n");
      out.write("\r\n");
      out.write("function 좋아요(like,board,writer){\r\n");
      out.write("\tvar likes={\"like\":like,\"writer\":{sn:writer},\"board\":{sn:board}};\r\n");
      out.write("\t $.ajax({url:\"/like\",  \r\n");
      out.write("\t     success:function(result,status){\r\n");
      out.write("\t    \t console.log(result),\r\n");
      out.write("\t    \t 좋아요갯수(board);\r\n");
      out.write("\t    \t 좋아요여부(board,writer);\r\n");
      out.write("\t     \t},\r\n");
      out.write("\t    \t error:function(){\r\n");
      out.write("\t    \t console.log(\"실패하였습니다\"); \r\n");
      out.write("\t    \t\t},\r\n");
      out.write("        type:\"POST\",\r\n");
      out.write("        contentType:\"application/json; charset=utf-8\",\r\n");
      out.write("        data :JSON.stringify(likes)\r\n");
      out.write("       });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function 좋아요전환(){\r\n");
      out.write("\tvar likes=$('#likes').val();\r\n");
      out.write("\tconsole.log(\"like값=\"+likes);\r\n");
      out.write("\tif(likes==1){\r\n");
      out.write("\t\t$('#likes').val(0);\r\n");
      out.write("\t\t$(\"#like\").removeClass(\"like\");\r\n");
      out.write("\t\tconsole.log(\"like=1일때\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\t$('#likes').val(1);\r\n");
      out.write("\t\t$(\"#like\").addClass(\"like\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log(\"like=0일때\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t좋아요($('#likes').val());\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function 좋아요여부(board,writer){\r\n");
      out.write("\tvar likes={\"writer\":{sn:writer},\"board\":{sn:board}};\r\n");
      out.write("\t\r\n");
      out.write("\t $.ajax({url:\"/likeis\",  \r\n");
      out.write("\t     success:function(result,status){\r\n");
      out.write("\t    \t console.log(result),\r\n");
      out.write("\t    \t $(\"#like\"+board).html(result),\r\n");
      out.write("\t    \t console.log(\"성공\"); \r\n");
      out.write("\t     \t},\r\n");
      out.write("\t    \t error:function(){\r\n");
      out.write("\t    \t console.log(\"실패\"); \r\n");
      out.write("\t    \t\t},\r\n");
      out.write("        type:\"POST\",\r\n");
      out.write("        contentType:\"application/json; charset=utf-8\",\r\n");
      out.write("        data :JSON.stringify(likes)\r\n");
      out.write("       });\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function 좋아요갯수(sn){\r\n");
      out.write("\t\r\n");
      out.write("\t $.ajax({url:\"/like/\"+sn,\r\n");
      out.write("\t     success:function(result,status){\r\n");
      out.write("\t    \t console.log(result),\r\n");
      out.write("\t    \t $(\"#box\"+sn).html(result),\r\n");
      out.write("\t    \t console.log(\"등록되었습니다\"); \r\n");
      out.write("\r\n");
      out.write("\t     \t},\r\n");
      out.write("\t    \t error:function(){\r\n");
      out.write("\t    \t console.log(\"실패\"); \r\n");
      out.write("\t    \t\t},\r\n");
      out.write("       type:\"POST\"\r\n");
      out.write("      });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function 댓글(board,profile,commentsize){\r\n");
      out.write("\r\n");
      out.write("\tvar or = $(\"#comments\"+board).val(); \r\n");
      out.write("\tif(or==\"댓글\"){\r\n");
      out.write("\t\t댓글출력(board,profile,commentsize);\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\t$(\"#comments\"+board).val(\"댓글\");\r\n");
      out.write("\t\t$(\"#comment\"+board).empty();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function 댓글출력(board,profile,commentsize){\r\n");
      out.write("\tcommentsize = commentsize +3;\r\n");
      out.write("\t $.ajax({url:\"/comment/\"+board,\r\n");
      out.write("\t\t    data : {\"profile\":profile,\"commentsize\":commentsize},\r\n");
      out.write("    success : function(data) {\r\n");
      out.write("    $(\"#comment\"+board).html(data),\r\n");
      out.write("    $(\"#comments\"+board).val(\"댓글닫기\");\r\n");
      out.write("\t    },\r\n");
      out.write("\t    error:function(){console.log(\"실패\");},\r\n");
      out.write("    type:\"POST\"\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function 댓글달기(board){\r\n");
      out.write("\tvar comment={contents:$(\"#commentcontent\"+board).val(), \"writer\":{sn:");
      out.print(session.getAttribute("sn"));
      out.write("},\"board\":{sn:board}};\r\n");
      out.write("\tconsole.log(comment);\r\n");
      out.write("\t $.ajax({url:\"/comment\",  \r\n");
      out.write("\t     success:function(result,status){\r\n");
      out.write("\t    \t $(\"#commentcontent\"+board).val(\"\");\r\n");
      out.write("\t    \t $(\"#plus\"+board).after(result);\r\n");
      out.write("\t    \t 좋아요갯수(board);\r\n");
      out.write("\t     \t},\r\n");
      out.write("\t    \t error:function(){\r\n");
      out.write("\t    \t console.log(\"실패하였습니다\"); \r\n");
      out.write("\t    \t\t},\r\n");
      out.write("       type:\"POST\",\r\n");
      out.write("       contentType:\"application/json; charset=utf-8\",\r\n");
      out.write("       data :JSON.stringify(comment)\r\n");
      out.write("      });\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function 댓글삭제(no,board){\r\n");
      out.write("\t $.ajax({url:\"/deletecom/\"+no,\r\n");
      out.write(" \tsuccess : function(data) {\r\n");
      out.write(" \talert(data);\r\n");
      out.write(" \t$(\"#eachcomment\"+no).remove();\r\n");
      out.write(" \t좋아요갯수(board);\r\n");
      out.write("\t    },\r\n");
      out.write("\t    error:function(){console.log(\"실패\");},\r\n");
      out.write(" type:\"POST\"\r\n");
      out.write(" });\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function 사진출력(sn){\r\n");
      out.write("\t\r\n");
      out.write("\t $.ajax({url:\"/photo/\"+sn,\r\n");
      out.write("\t\t  \tsuccess : function(data) {\r\n");
      out.write("\t\t  \t\t$(\"#photo\"+sn).html(data);\r\n");
      out.write("\t\t\t    },\r\n");
      out.write("\t\t\terror:function(){console.log(\"실패\");},\r\n");
      out.write("\t\t  type:\"POST\"\r\n");
      out.write("\t\t  });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function 게시물삭제(board){\r\n");
      out.write("\t $.ajax({url:\"/deleteboard/\"+board,\r\n");
      out.write("\t\t  \tsuccess : function(data) {\r\n");
      out.write("\t\t\talert(data);\r\n");
      out.write("\t\t  \tlocation.reload();\r\n");
      out.write("\t\t\t    },\r\n");
      out.write("\t\t\t    error:function(){console.log(\"실패\");},\r\n");
      out.write("\t\t  type:\"POST\"\r\n");
      out.write("\t\t  });}\r\n");
      out.write("\r\n");
      out.write("function 공유글(board){\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t $.ajax({url:\"/sharing/\"+board,\r\n");
      out.write("\t\t  \tsuccess : function(data) {\r\n");
      out.write("\t\t  \t$(\"#sharing\"+board).html(data);\r\n");
      out.write("\t\t\t    },\r\n");
      out.write("\t\t\t    error:function(){console.log(\"실패\");},\r\n");
      out.write("\t\t  type:\"POST\"\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("function person(sn){\r\n");
      out.write("\tparent.person(sn);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("window.addEventListener('scroll', () => { \r\n");
      out.write("\tlet scrollLocation = document.documentElement.scrollTop; // 현재 스크롤바 위치\r\n");
      out.write("\tlet windowHeight = window.innerHeight; // 스크린 창\r\n");
      out.write("\tlet fullHeight = document.body.scrollHeight; //  margin 값은 포함 x\r\n");
      out.write("\r\n");
      out.write("\tif(scrollLocation + windowHeight + 300 >= fullHeight){\r\n");
      out.write("\t\t게시물로드(3);\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("<!--이부분 07 13 추가  -->\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          if (_jspx_meth_c_005fwhen_005f3(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/board/personPage.jsp(98,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request eq 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<button class=\"btn hover1 friendbt\" onclick=\"친구신청()\"><b>친구신청</b></button>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/board/personPage.jsp(102,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request eq 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<button class=\"btn hover1 friendbt\" onclick=\"친구수락()\"><b>친구수락</b></button>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/board/personPage.jsp(106,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request eq 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<button class=\"btn hover1 friendbt\" onclick=\"\">친구</button>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f3 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f3_reused = false;
    try {
      _jspx_th_c_005fwhen_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/board/personPage.jsp(110,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request eq 4}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f3 = _jspx_th_c_005fwhen_005f3.doStartTag();
      if (_jspx_eval_c_005fwhen_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<button class=\"btn hover1 friendbt\" onclick=\"\">신청중</button>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
      _jspx_th_c_005fwhen_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<!-- <button class=\"btn hover1 friendbt\" onclick=\"\">ㅋㅋ</button> -->\r\n");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
