/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-08-26 12:26:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.lec206.acebook.util.BIRTH;

public final class 주소변경창_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.lec206.acebook.util.BIRTH");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("html {\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    background: #f5f6f7;\r\n");
      out.write("    font-family: Dotum,'돋움',Helvetica,sans-serif;\r\n");
      out.write("}\r\n");
      out.write("#logo {\r\n");
      out.write("    width: 240px;\r\n");
      out.write("    height: 44px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#header {\r\n");
      out.write("    padding-top: 62px;\r\n");
      out.write("    padding-bottom: 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("#wrapper {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    transform: translate(-50%);\r\n");
      out.write("    width: 460px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 입력폼 */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("h3 {\r\n");
      out.write("    margin: 19px 0 8px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".box {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 51px;\r\n");
      out.write("    border: solid 1px #dadada;\r\n");
      out.write("    padding: 10px 14px 10px 14px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".int {\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 29px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("    font-family: Dotum,'돋움',Helvetica,sans-serif;    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box.int_id {\r\n");
      out.write("    padding-right: 110px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box.int_pass {\r\n");
      out.write("    padding-right: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box.int_pass_check {\r\n");
      out.write("    padding-right: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".pswdImg {\r\n");
      out.write("    width: 18px;\r\n");
      out.write("    height: 20px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    right: 16px;\r\n");
      out.write("    margin-top: -10px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_wrap {\r\n");
      out.write("    display: table;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_yy {\r\n");
      out.write("    display: table-cell;\r\n");
      out.write("    width: 147px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_mm {\r\n");
      out.write("    display: table-cell;\r\n");
      out.write("    width: 147px;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_dd {\r\n");
      out.write("    display: table-cell;\r\n");
      out.write("    width: 147px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_mm, #bir_dd {\r\n");
      out.write("    padding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 29px;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    background: #fff url(https://static.nid.naver.com/images/join/pc/sel_arr_2x.gif) 100% 50% no-repeat;\r\n");
      out.write("    background-size: 20px 8px;\r\n");
      out.write("    -webkit-appearance: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    text-align: start;\r\n");
      out.write("    border: none;\r\n");
      out.write("    cursor: default;\r\n");
      out.write("    font-family: Dotum,'돋움',Helvetica,sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 버튼 */\r\n");
      out.write("\r\n");
      out.write(".btn_area {\r\n");
      out.write("    margin: 30px 0 91px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnJoin {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 21px 0 17px;\r\n");
      out.write("    border: 0;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    color: white;\r\n");
      out.write("    background-color: skyblue;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    font-family: Dotum,'돋움',Helvetica,sans-serif;\r\n");
      out.write("}\r\n");
      out.write("#btnJoin:hover{\r\n");
      out.write("color:black;\r\n");
      out.write("background-color: DodgerBlue;\r\n");
      out.write("}\r\n");
      out.write(".button{\r\n");
      out.write("\r\n");
      out.write("background-color: gray; \r\n");
      out.write(" background-color: white;\r\n");
      out.write("  color: black;\r\n");
      out.write("  border: 2px solid #e7e7e7;\r\n");
      out.write("  font-size:18px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".button:hover {\r\n");
      out.write(" background-color: #e7e7e7;\r\n");
      out.write("}\r\n");
      out.write(".button:active {\r\n");
      out.write("  background-color: lightblue;\r\n");
      out.write("  box-shadow: 0 1px #666;\r\n");
      out.write("  transform: translateY(1px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button2{\r\n");
      out.write("\r\n");
      out.write("background-color: LightGray;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: black;\r\n");
      out.write("  padding: 10px 60px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<form action=\"changepost\" method=\"post\">\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("            <!-- content-->\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("                <!-- ID -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h3 class=\"join_title\">\r\n");
      out.write("                        <label for=\"id\">우편번호&nbsp;&nbsp;</label><input type=\"button\" onclick=\"sample4_execDaumPostcode()\" value=\"조회\"/>\r\n");
      out.write("                    </h3>\r\n");
      out.write("                    <span class=\"box int_id\">\r\n");
      out.write("                        <input type=\"text\" name=\"post\" id=\"post\" class=\"int\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.post.post ne null ? member.post.post : \" \"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"readonly/>\r\n");
      out.write("                        \r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"error_next_box\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- PW2 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h3 class=\"join_title\"><label for=\"pswd2\">주소</label></h3>\r\n");
      out.write("                    <span class=\"box int_pass_check\">\r\n");
      out.write("                       <input type=\"text\" name=\"address\" id=\"address\" class=\"int\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.post.address ne null ? member.post.address : \" \"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"readonly/><br>\r\n");
      out.write("                       \r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"error_next_box\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- NAME -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h3 class=\"join_title\"><label for=\"name\">상세주소</label></h3>\r\n");
      out.write("                    <span class=\"box int_name\">\r\n");
      out.write("                        <input type=\"text\" name=\"addresstail\" id=\"addresstail\" class=\"int\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.post.addresstail ne null ? member.post.addresstail : \" \"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><br>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"error_next_box\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- BIRTH -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h3 class=\"join_title\"><label for=\"yy\">출신지</label></h3>\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"bir_wrap\">\r\n");
      out.write("                        <!-- BIRTH_YY -->\r\n");
      out.write("                        <div id=\"bir_yy\">\r\n");
      out.write("                            <span class=\"box\">\r\n");
      out.write("                            <select id=\"birthpalce\" name=\"birthplace\">\r\n");
      out.write("                        ");
 for(BIRTH type : BIRTH.values()) { 
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print(type);
      out.write('"');
      out.write('>');
      out.print(type );
      out.write("</option>\r\n");
      out.write("                           ");
} 
      out.write("\r\n");
      out.write("                           </select>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- JOIN BTN-->\r\n");
      out.write("              <div class=\"btn_area\">\r\n");
      out.write("                    <input type=\"submit\" value=\"변경하기\" id=\"btnJoin\">                                    \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"btn_area\"></div>\r\n");
      out.write("                <button type=\"button\"  class=\"button2\" id=\"btnJoin2\" onclick=\"self.close()\">취소</button>\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("            </div> \r\n");
      out.write("            <!-- content-->\r\n");
      out.write("\r\n");
      out.write("        </div> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!-- javaScript -->\r\n");
      out.write("<script>\r\n");
      out.write("    //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("    function sample4_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var roadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("                var extraRoadAddr = ''; // 참고 항목 변수\r\n");
      out.write("\r\n");
      out.write("                // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                    extraRoadAddr += data.bname;\r\n");
      out.write("                }\r\n");
      out.write("                // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                }\r\n");
      out.write("                // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                if(extraRoadAddr !== ''){\r\n");
      out.write("                    extraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('post').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"address\").value = roadAddr;\r\n");
      out.write("                document.getElementById(\"addresstail\").focus();               \r\n");
      out.write("               \r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
