/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-08-26 12:26:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 학교변경창_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"js/myjs.js\"></script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>학교변경창</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    background: #f5f6f7;\r\n");
      out.write("    font-family: Dotum,'돋움',Helvetica,sans-serif;\r\n");
      out.write("}\r\n");
      out.write("#logo {\r\n");
      out.write("    width: 240px;\r\n");
      out.write("    height: 44px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#header {\r\n");
      out.write("    padding-top: 62px;\r\n");
      out.write("    padding-bottom: 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("#wrapper {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    transform: translate(-50%);\r\n");
      out.write("    width: 460px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 입력폼 */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("h3 {\r\n");
      out.write("    margin: 19px 0 8px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".box {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 51px;\r\n");
      out.write("    border: solid 1px #dadada;\r\n");
      out.write("    padding: 10px 14px 10px 14px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".int {\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 29px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("    font-family: Dotum,'돋움',Helvetica,sans-serif;    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box.int_id {\r\n");
      out.write("    padding-right: 110px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box.int_pass {\r\n");
      out.write("    padding-right: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box.int_pass_check {\r\n");
      out.write("    padding-right: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".pswdImg {\r\n");
      out.write("    width: 18px;\r\n");
      out.write("    height: 20px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    right: 16px;\r\n");
      out.write("    margin-top: -10px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_wrap {\r\n");
      out.write("    display: table;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_yy {\r\n");
      out.write("    display: table-cell;\r\n");
      out.write("    width: 147px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_mm {\r\n");
      out.write("    display: table-cell;\r\n");
      out.write("    width: 147px;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_dd {\r\n");
      out.write("    display: table-cell;\r\n");
      out.write("    width: 147px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_mm, #bir_dd {\r\n");
      out.write("    padding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 29px;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    background: #fff url(https://static.nid.naver.com/images/join/pc/sel_arr_2x.gif) 100% 50% no-repeat;\r\n");
      out.write("    background-size: 20px 8px;\r\n");
      out.write("    -webkit-appearance: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    text-align: start;\r\n");
      out.write("    border: none;\r\n");
      out.write("    cursor: default;\r\n");
      out.write("    font-family: Dotum,'돋움',Helvetica,sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 버튼 */\r\n");
      out.write("\r\n");
      out.write(".btn_area {\r\n");
      out.write("    margin: 30px 0 91px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnJoin {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 21px 0 17px;\r\n");
      out.write("    border: 0;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    color: white;\r\n");
      out.write("    background-color: skyblue;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    font-family: Dotum,'돋움',Helvetica,sans-serif;\r\n");
      out.write("}\r\n");
      out.write("#btnJoin:hover{\r\n");
      out.write("color:black;\r\n");
      out.write("background-color: DodgerBlue;\r\n");
      out.write("}\r\n");
      out.write(".button{\r\n");
      out.write("\r\n");
      out.write("background-color: gray; \r\n");
      out.write(" background-color: white;\r\n");
      out.write("  color: black;\r\n");
      out.write("  border: 2px solid #e7e7e7;\r\n");
      out.write("  font-size:18px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".button:hover {\r\n");
      out.write(" background-color: #e7e7e7;\r\n");
      out.write("}\r\n");
      out.write(".button:active {\r\n");
      out.write("  background-color: lightblue;\r\n");
      out.write("  box-shadow: 0 1px #666;\r\n");
      out.write("  transform: translateY(1px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button2{\r\n");
      out.write("\r\n");
      out.write("background-color: LightGray;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: black;\r\n");
      out.write("  padding: 10px 60px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item{\r\n");
      out.write("\r\n");
      out.write("width: 100%;\r\n");
      out.write("    height: 29px;\r\n");
      out.write("  font-size:20px;\r\n");
      out.write("  background-color:transparent;border:0 solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"changeschool\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<!-- wrapper -->\r\n");
      out.write("        <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("            <!-- content-->\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("                <!-- ID -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h3 class=\"join_title\">\r\n");
      out.write("                        <label for=\"id\">초등학교</label>\r\n");
      out.write("                    </h3>\r\n");
      out.write("                    <span class=\"box int_id\">\r\n");
      out.write("                        <input type=\"text\" class=\"item\" id=\"row\" name=\"row\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.school.row ne null ? member.school.row : \"\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                        \r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"error_next_box\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                 <div>\r\n");
      out.write("                    <h3 class=\"join_title\">\r\n");
      out.write("                        <label for=\"id\">중학교</label>\r\n");
      out.write("                    </h3>\r\n");
      out.write("                    <span class=\"box int_id\">\r\n");
      out.write("                        <input type=\"text\"  class=\"item\" id=\"middle\" name=\"middle\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.school.middle ne null ? member.school.middle : \"\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                        \r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"error_next_box\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                 <div>\r\n");
      out.write("                    <h3 class=\"join_title\">\r\n");
      out.write("                        <label for=\"id\">고등학교</label>\r\n");
      out.write("                    </h3>\r\n");
      out.write("                    <span class=\"box int_id\">\r\n");
      out.write("                        <input type=\"text\" class=\"item\" id=\"high\" name=\"high\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.school.high ne null ? member.school.high : \"\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                        \r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"error_next_box\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                 <div>\r\n");
      out.write("                    <h3 class=\"join_title\">\r\n");
      out.write("                        <label for=\"id\">대학교</label>\r\n");
      out.write("                    </h3>\r\n");
      out.write("                    <span class=\"box int_id\">\r\n");
      out.write("                        <input type=\"text\" class=\"item\" id=\"university\" name=\"university\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.school.university ne null ? member.school.university : \"\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                        \r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"error_next_box\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- JOIN BTN-->\r\n");
      out.write("              <div class=\"btn_area\">\r\n");
      out.write("                    <input type=\"submit\" value=\"변경하기\" id=\"btnJoin\">                                    \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                 <div class=\"btn_area\"></div>\r\n");
      out.write("                <button type=\"button\"  class=\"button2\" id=\"btnJoin2\" onclick=\"self.close()\">취소</button>\r\n");
      out.write("            </div>                \r\n");
      out.write("\r\n");
      out.write("            </div> \r\n");
      out.write("            <!-- content-->\r\n");
      out.write("\r\n");
      out.write("        </div> \r\n");
      out.write("        <!-- wrapper -->\r\n");
      out.write("    <script src=\"main.js\"></script>\r\n");
      out.write("    </form>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
