/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-08-28 11:56:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 회원등록창_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"js/myjs.js\"></script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원등록</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    background: #f5f6f7;\r\n");
      out.write("    font-family: Dotum,'돋움',Helvetica,sans-serif;\r\n");
      out.write("}\r\n");
      out.write("#logo {\r\n");
      out.write("    width: 240px;\r\n");
      out.write("    height: 44px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#header {\r\n");
      out.write("    padding-top: 62px;\r\n");
      out.write("    padding-bottom: 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("#wrapper {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    transform: translate(-50%);\r\n");
      out.write("    width: 460px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 입력폼 */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("h3 {\r\n");
      out.write("    margin: 19px 0 8px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".box {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 51px;\r\n");
      out.write("    border: solid 1px #dadada;\r\n");
      out.write("    padding: 10px 14px 10px 14px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".int {\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 29px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("    font-family: Dotum,'돋움',Helvetica,sans-serif;    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box.int_id {\r\n");
      out.write("    padding-right: 110px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box.int_pass {\r\n");
      out.write("    padding-right: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box.int_pass_check {\r\n");
      out.write("    padding-right: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".pswdImg {\r\n");
      out.write("    width: 18px;\r\n");
      out.write("    height: 20px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    right: 16px;\r\n");
      out.write("    margin-top: -10px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_wrap {\r\n");
      out.write("    display: table;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_yy {\r\n");
      out.write("    display: table-cell;\r\n");
      out.write("    width: 147px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_mm {\r\n");
      out.write("    display: table-cell;\r\n");
      out.write("    width: 147px;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_dd {\r\n");
      out.write("    display: table-cell;\r\n");
      out.write("    width: 147px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bir_mm, #bir_dd {\r\n");
      out.write("    padding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 29px;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    background: #fff url(https://static.nid.naver.com/images/join/pc/sel_arr_2x.gif) 100% 50% no-repeat;\r\n");
      out.write("    background-size: 20px 8px;\r\n");
      out.write("    -webkit-appearance: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    text-align: start;\r\n");
      out.write("    border: none;\r\n");
      out.write("    cursor: default;\r\n");
      out.write("    font-family: Dotum,'돋움',Helvetica,sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 버튼 */\r\n");
      out.write("\r\n");
      out.write(".btn_area {\r\n");
      out.write("    margin: 30px 0 91px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnJoin {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 21px 0 17px;\r\n");
      out.write("    border: 0;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    color: white;\r\n");
      out.write("    background-color: skyblue;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    font-family: Dotum,'돋움',Helvetica,sans-serif;\r\n");
      out.write("}\r\n");
      out.write("#btnJoin:hover{\r\n");
      out.write("color:black;\r\n");
      out.write("background-color: DodgerBlue;\r\n");
      out.write("}\r\n");
      out.write(".button{\r\n");
      out.write("\r\n");
      out.write("background-color: gray; \r\n");
      out.write(" background-color: white;\r\n");
      out.write("  color: black;\r\n");
      out.write("  border: 2px solid #e7e7e7;\r\n");
      out.write("  font-size:18px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".button:hover {\r\n");
      out.write(" background-color: #e7e7e7;\r\n");
      out.write("}\r\n");
      out.write(".button:active {\r\n");
      out.write("  background-color: lightblue;\r\n");
      out.write("  box-shadow: 0 1px #666;\r\n");
      out.write("  transform: translateY(1px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button2{\r\n");
      out.write("\r\n");
      out.write("background-color: LightGray;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: black;\r\n");
      out.write("  padding: 10px 60px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form onsubmit=\"return 회원등록하다()\" action=\"member\" method=\"post\"><!--onsubmit>>>return 값이 true 일때실행  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- wrapper -->\r\n");
      out.write("        <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("            <!-- content-->\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("                <!-- ID -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h3 class=\"join_title\">\r\n");
      out.write("                        <label for=\"id\">아이디&nbsp;&nbsp;<input class=\"button\" type=\"button\" onclick=\"아이디중복검사창을띄우다()\" value=\"중복검사\"></label>\r\n");
      out.write("                    </h3>\r\n");
      out.write("                    <span class=\"box int_id\">\r\n");
      out.write("                        <input type=\"text\" name =\"id\" id=\"id\" class=\"int\" maxlength=\"20\" readonly>\r\n");
      out.write("                        \r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"error_next_box\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- PW1 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h3 class=\"join_title\"><label for=\"pswd1\">비밀번호</label></h3>\r\n");
      out.write("                    <span class=\"box int_pass\">\r\n");
      out.write("                        <input type=\"password\" name=\"password\" id=\"password1\" class=\"int\" maxlength=\"20\">\r\n");
      out.write("                        <span id=\"alertTxt\"></span>\r\n");
      out.write("                       \r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"error_next_box\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- PW2 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h3 class=\"join_title\"><label for=\"pswd2\">비밀번호 재확인</label></h3>\r\n");
      out.write("                    <span class=\"box int_pass_check\">\r\n");
      out.write("                        <input type=\"password\" id=\"password2\" class=\"int\" maxlength=\"20\">\r\n");
      out.write("                       \r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"error_next_box\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- NAME -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h3 class=\"join_title\"><label for=\"name\">이름</label></h3>\r\n");
      out.write("                    <span class=\"box int_name\">\r\n");
      out.write("                        <input type=\"text\" id=\"name\" name=\"name\" class=\"int\" maxlength=\"20\">\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"error_next_box\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- BIRTH -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h3 class=\"join_title\"><label for=\"yy\">생년월일</label></h3>\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"bir_wrap\">\r\n");
      out.write("                        <!-- BIRTH_YY -->\r\n");
      out.write("                        <div id=\"bir_yy\">\r\n");
      out.write("                            <span class=\"box\">\r\n");
      out.write("                                <input type=\"text\" name=\"year\" id=\"year\" class=\"int\" maxlength=\"4\" placeholder=\"년(4자)\">\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- BIRTH_MM -->\r\n");
      out.write("                        <div id=\"bir_mm\">\r\n");
      out.write("                            <span class=\"box\">\r\n");
      out.write("                                <select id=\"month\" name=\"month\" class=\"sel\">\r\n");
      out.write("                                    <option>월</option>\r\n");
      out.write("                                    ");
 for (int i=1; i<=9; i++){ 
      out.write("\r\n");
      out.write("                                        <option value=\"");
      out.print( "0"+i );
      out.write('"');
      out.write('>');
      out.print("0"+ i );
      out.write("</option>\r\n");
      out.write("                                        ");
} 
      out.write("\r\n");
      out.write("                                       ");
 for (int i=10; i<=12; i++){ 
      out.write("\r\n");
      out.write("                                        <option value=\"");
      out.print(i );
      out.write('"');
      out.write('>');
      out.print(i );
      out.write("</option>\r\n");
      out.write("                                        ");
} 
      out.write("\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- BIRTH_DD -->\r\n");
      out.write("                        <div id=\"bir_dd\">\r\n");
      out.write("                            <span class=\"box\">\r\n");
      out.write("                                <select id=\"day\" name=\"day\">\r\n");
      out.write("                                    <option value=\"\">일</option>\r\n");
      out.write("                                    ");
for(int i=1; i<=9; i++){ 
      out.write("\r\n");
      out.write("                                    <option value=\"");
      out.print("0"+i);
      out.write('"');
      out.write('>');
      out.print("0"+i);
      out.write("</option>\r\n");
      out.write("                                    ");
} 
      out.write("\r\n");
      out.write("                                    ");
for(int i=10; i<=31; i++){ 
      out.write("\r\n");
      out.write("                                    <option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");
      out.write("                                    ");
} 
      out.write("\r\n");
      out.write("                                </select>                            \r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>                             \r\n");
      out.write("                </div>                      \r\n");
      out.write("<input type=\"hidden\" name=\"age\" id=\"age\"/>\r\n");
      out.write("                 <!-- GENDER -->\r\n");
      out.write("                 <div>\r\n");
      out.write("                    <h3 class=\"join_title\"><label for=\"gender\">성별</label></h3>\r\n");
      out.write("                    <span class=\"box gender_code\">\r\n");
      out.write("                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    남성<input type=\"radio\" name=\"gender\" value=\"남자\" id=\"man\" checked>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;여성<input type=\"radio\" name=\"gender\" value=\"여자\" id=\"woman\">         \r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- JOIN BTN-->\r\n");
      out.write("              <div class=\"btn_area\">\r\n");
      out.write("                    <input type=\"submit\" value=\"가입하기\" id=\"btnJoin\">                                    \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- <div class=\"btn_area\"></div>\r\n");
      out.write("                <button type=\"button\"  class=\"button2\" id=\"btnJoin2\" onclick=\"self.close()\">취소</button>\r\n");
      out.write("            </div> -->\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("            </div> \r\n");
      out.write("            <!-- content-->\r\n");
      out.write("\r\n");
      out.write("        </div> \r\n");
      out.write("        <!-- wrapper -->\r\n");
      out.write("    <script src=\"main.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("    <input id=\"close\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></input>\r\n");
      out.write("</html>\r\n");
      out.write("<!-- <input type=\"hidden\" name=\"age\" id=\"age\"/><br><br>\r\n");
      out.write("성별&nbsp;&nbsp;&nbsp;남성<input type=\"radio\" name=\"gender\" value=\"남자\" id=\"man\" checked>여성<input type=\"radio\" name=\"gender\" value=\"여자\" id=\"woman\"><br><br>\r\n");
      out.write("<input type=\"submit\" value=\"회원가입\"/> <button type=\"button\" onclick=\"location.href='main'\">취소</button> -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function 아이디중복검사창을띄우다(){\r\n");
      out.write("   window.open(\"/id\",\" \",\"width=450,height=300\")\r\n");
      out.write("}\r\n");
      out.write("function 아이디를받다(id){\r\n");
      out.write("   let txtID=document.querySelector(\"#id\");\r\n");
      out.write("   txtID.value=id;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function 회원등록하다(){\r\n");
      out.write("   //필수 입력확인\r\n");
      out.write("   var txt성명=document.querySelector(\"#name\");\r\n");
      out.write("   if(txt성명.value==\"\"){\r\n");
      out.write("      alert(\"성명은 필수 입력입니다\")\r\n");
      out.write("      return false;\r\n");
      out.write("   \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   var txtID=document.querySelector(\"#id\");\r\n");
      out.write("   if(txtID.value==\"\"){\r\n");
      out.write("      alert(\"아이디는 필수 입력입니다\")\r\n");
      out.write("      return false;// =서브밋중단\r\n");
      out.write("   \r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   var txt패스워드=document.querySelector(\"#password1\");\r\n");
      out.write("   if(txt패스워드.value==\"\"){\r\n");
      out.write("      alert(\"패스워드는 필수 입력입니다.\")      \r\n");
      out.write("      return false;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   //비밀번호 동일 확인\r\n");
      out.write("   var txt패스워드2=document.querySelector(\"#password2\");\r\n");
      out.write("   if(txt패스워드.value !=txt패스워드2.value){\r\n");
      out.write("      alert(\"패스워드가 동일하지 않습니다\")\r\n");
      out.write("      return false;   \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   var txtyear=document.querySelector(\"#year\")\r\n");
      out.write("   if(txtyear.value==\"\"){\r\n");
      out.write("      alert(\"출생연도를 입력해주세요\");\r\n");
      out.write("      return false;\r\n");
      out.write("   }\r\n");
      out.write("   var txtmonth=document.querySelector(\"#month\")\r\n");
      out.write("   if(txtmonth.value==\"\"){\r\n");
      out.write("      alert(\"월을 선택하세요\");\r\n");
      out.write("      return false;\r\n");
      out.write("   }\r\n");
      out.write("   var txtday=document.querySelector(\"#day\")\r\n");
      out.write("   if(txtday.value==\"\"){\r\n");
      out.write("      alert(\"일을 선택하세요\");\r\n");
      out.write("      return false;\r\n");
      out.write("   }\r\n");
      out.write("   var txtall=document.querySelector(\"#age\")\r\n");
      out.write("   txtall.value=txtyear.value+'-'+txtmonth.value+'-'+txtday.value;\r\n");
      out.write("      \r\n");
      out.write("    var check=/^(?=.*[A-Za-z])(?=.*\\d)(?=.*[$@$!%*#?&])[A-Za-z\\d$@$!%*#?&]{8,}$/; //최소8자 문자 숫자 특수문자 포함\r\n");
      out.write("    var check2=/[0-9]/; //숫자만\r\n");
      out.write("    var check3=/[ ~!@#$%^&*()_+|<>?:{}]/; //특수문자\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   if(!check.test(txt패스워드.value)){\r\n");
      out.write("      alert(\"비밀번호를 영문,숫자,특수문자의 조합으로 입력해주세요.\")\r\n");
      out.write("      return false;\r\n");
      out.write("   }\r\n");
      out.write("    \r\n");
      out.write("    if(!check2.test(txtyear.value)){\r\n");
      out.write("      alert(\"출생연도는 숫자만 입력 가능합니다\")\r\n");
      out.write("      return false;\r\n");
      out.write("   }\r\n");
      out.write("    \r\n");
      out.write("    if(check3.test(txt성명.value)){\r\n");
      out.write("      alert(\"올바른 이름 형식이 아닙니다.\")\r\n");
      out.write("      return false;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   alert(\"가입이 완료되었습니다\");\r\n");
      out.write("   return true;/*위의값들이 모두 만족하였을때 트루값 반환  */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("window.onload = function (){ \r\n");
      out.write("\t   \r\n");
      out.write("\tlet 종료 = document.querySelector(\"#close\");\r\n");
      out.write("\t\r\n");
      out.write("      if(종료.value==\"close\"){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tparent.close_layer();\r\n");
      out.write("\t\tparent.move();\r\n");
      out.write("\t\t\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
