/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-08-26 12:03:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.friend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 친구_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1624095629010L));
    _jspx_dependants.put("jar:file:/C:/Users/cholc/Desktop/hm/project_sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/acebookXMLVer2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("/*  a:link { color: white; text-decoration: none;} */\r\n");
      out.write("  a:hover { color:B2CCCE; text-decoration: none;}\r\n");
      out.write("  a:link { color:B2CCCE; text-decoration: none;}\r\n");
      out.write("  a { color: skyblue; }\r\n");
      out.write("  \r\n");
      out.write(".main{\r\n");
      out.write("float:left;\r\n");
      out.write("}\r\n");
      out.write(".jb-wrap {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            margin: 10px auto;\r\n");
      out.write("            border: none;\r\n");
      out.write("            float:left;\r\n");
      out.write("            margin-left : 20px;\r\n");
      out.write("         }\r\n");
      out.write("         .jb-wrap img {\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            height:150px;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("         }\r\n");
      out.write("         .jb-text {\r\n");
      out.write("            padding: 5px 10px;\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            background-color:#F2F3F5;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-radius : 3px;\r\n");
      out.write("            \r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-wrap:nowrap;\r\n");
      out.write("  background: white;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  padding : auto;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#leftmenu{\r\n");
      out.write("\r\n");
      out.write("padding : 10;\r\n");
      out.write("  height: 2000px;\r\n");
      out.write("  width: 20%;\r\n");
      out.write("  order: 1;\r\n");
      out.write("  background: #F2F3F5;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#friendlistmenu{\r\n");
      out.write("\r\n");
      out.write("padding : 10;\r\n");
      out.write("  height: 800px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  order: 2;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".items {\r\n");
      out.write("font-size : 18px;\r\n");
      out.write("   margin-left : 7px;\r\n");
      out.write("   margin-right : 7px;\r\n");
      out.write("  /* margin-top : 8px; */\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  background: #F2F3F5;\r\n");
      out.write("  width : 270px;\r\n");
      out.write("  height : 60px;\r\n");
      out.write("  border : none;\r\n");
      out.write("  border-radius : 10px;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".items:hover{\r\n");
      out.write("/* background: #DDD5F0; */\r\n");
      out.write("background: skyblue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"leftmenu\">\r\n");
      out.write("<h3>친구</h3>\r\n");
      out.write("<button class=\"items\" type=\"button\" onclick=\"친구요청()\">받은친구요청</button>\r\n");
      out.write("<button class=\"items\" type=\"button\" onclick=\"요청한친구()\">요청한친구목록</button>\r\n");
      out.write("<button class=\"items\" type=\"button\" onclick=\"나이추천()\">나이가 같은 사람</button>\r\n");
      out.write("<button class=\"items\" type=\"button\" onclick=\"학교추천()\">학교가 같은 사람</button>\r\n");
      out.write("<button class=\"items\" type=\"button\" onclick=\"모든친구()\">모든친구</button>\r\n");
      out.write("<button class=\"items\" type=\"button\" onclick=\"location.href=''\">생일</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"friendlistmenu\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function 추천목록(){\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function 친구요청(){\r\n");
      out.write("   $.ajax({url:\"requests\",\r\n");
      out.write("      type:\"POST\",\r\n");
      out.write("      contentType:\"application/json; charset=utf-8\",//서버에서제이슨으로보내고\r\n");
      out.write("      dataType:\"text\",//서버에서받아오고 text html png 등으로 받을수도있음\r\n");
      out.write("      success:function(result){\r\n");
      out.write("   $(\"#friendlistmenu\").html(result);\r\n");
      out.write("      }});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function 모든친구(){\r\n");
      out.write("   $.ajax({url:\"myfriends\",\r\n");
      out.write("      type:\"POST\",\r\n");
      out.write("      contentType:\"application/json; charset=utf-8\",//서버에서제이슨으로보내고\r\n");
      out.write("      dataType:\"text\",//서버에서받아오고 text html png 등으로 받을수도있음\r\n");
      out.write("      success:function(result){\r\n");
      out.write("   $(\"#friendlistmenu\").html(result);\r\n");
      out.write("      }});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function 요청한친구(){\r\n");
      out.write("   $.ajax({url:\"requested\",\r\n");
      out.write("      type:\"POST\",\r\n");
      out.write("      contentType:\"application/json; charset=utf-8\",//서버에서제이슨으로보내고\r\n");
      out.write("      dataType:\"text\",//서버에서받아오고 text html png 등으로 받을수도있음\r\n");
      out.write("      success:function(result){\r\n");
      out.write("   $(\"#friendlistmenu\").html(result);\r\n");
      out.write("      }});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function 나이추천(){ //나이가같은사람추천\r\n");
      out.write("   $.ajax({url:\"commendage\",\r\n");
      out.write("      type:\"POST\",\r\n");
      out.write("      contentType:\"application/json; charset=utf-8\",//서버에서제이슨으로보내고\r\n");
      out.write("      dataType:\"text\",//서버에서받아오고 text html png 등으로 받을수도있음\r\n");
      out.write("      success:function(result){\r\n");
      out.write("   $(\"#friendlistmenu\").html(result);\r\n");
      out.write("      }});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function 학교추천(){ //학교가같은사람추천\r\n");
      out.write("   $.ajax({url:\"commendschool\",\r\n");
      out.write("      type:\"POST\",\r\n");
      out.write("      contentType:\"application/json; charset=utf-8\",//서버에서제이슨으로보내고\r\n");
      out.write("      dataType:\"text\",//서버에서받아오고 text html png 등으로 받을수도있음\r\n");
      out.write("      success:function(result){\r\n");
      out.write("   $(\"#friendlistmenu\").html(result);\r\n");
      out.write("      }});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("function move(sn){\r\n");
      out.write("\tparent.person(sn);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
