/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-08-26 12:18:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.lec206.acebook.vo_member.Member;

public final class acebook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1624095629010L));
    _jspx_dependants.put("jar:file:/C:/Users/cholc/Desktop/hm/project_sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/acebookXMLVer2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.lec206.acebook.vo_member.Member");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

   HttpSession session= request.getSession(false);
	if(session!=null&& session.getAttribute("sn")==null){session=null;}

      out.write('\r');
      out.write('\n');
Member member = (Member)request.getAttribute("member"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- css , font, jq  -->\r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    color: gray;\r\n");
      out.write("}\r\n");
      out.write("body{ background-color: #F0F2F5;}\r\n");
      out.write("#nav{\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-flow: column nowrap;\r\n");
      out.write("  border: 0px solid green;\r\n");
      out.write("  margin:0px;\r\n");
      out.write("  height:auto;\r\n");
      out.write("  border-bottom:1px solid #E9EBEE;\r\n");
      out.write("  box-shadow: rgba(0, 0, 0, 0.15) 1.95px 1.95px 2.6px;\r\n");
      out.write("}\r\n");
      out.write("#con{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-wrap:nowrap;\r\n");
      out.write("}\r\n");
      out.write("#left{\r\n");
      out.write("padding : 10;\r\n");
      out.write("  height: 800px;\r\n");
      out.write("  width: 30%;\r\n");
      out.write("  order: 1;\r\n");
      out.write("}\r\n");
      out.write("#middle{\r\n");
      out.write("padding : 10;\r\n");
      out.write("  height: 800px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  order: 2;\r\n");
      out.write("}\r\n");
      out.write("#right{\r\n");
      out.write("padding : 10;\r\n");
      out.write("  height: 800px;\r\n");
      out.write("  width: 30%;\r\n");
      out.write("  order: 3;\r\n");
      out.write("}\r\n");
      out.write("#personleft{\r\n");
      out.write("padding : 10;\r\n");
      out.write("  height: 800px;\r\n");
      out.write("  width: 20%;\r\n");
      out.write("  order: 1;\r\n");
      out.write("}\r\n");
      out.write(".button2{\r\n");
      out.write("background-color: LightGray;\r\n");
      out.write("  border: 1px;\r\n");
      out.write("  color: black;\r\n");
      out.write("  padding: 10px 60px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".button2:hover{\r\n");
      out.write("background-color: white;\r\n");
      out.write("}\r\n");
      out.write(".divbar{display:flex; width: 100%; height: 50px; margin:0px;}\r\n");
      out.write(".divbarindex{padding:3px; margin:0px;  padding-left:5%; padding-right:5%; width:150px;display:flex;}\r\n");
      out.write(".pointer{cursor: pointer;}\r\n");
      out.write(".barindexbottom{border-bottom:4px solid #1877F2;}\r\n");
      out.write(".divbarleft{left:0px; margin-left:5px; margin-right:5px; display:flex;}\r\n");
      out.write(".divbarright{right:0px; margin-right:5px;  display:flex;}\r\n");
      out.write(".divbarmiddle{display:flex; margin-left:255px; padding-top:3px;}\r\n");
      out.write("#search{width:70%; height:30px; margin-top:6%; margin-left:6%;background-color: #F0F2F5; border-radius: 50px;}\r\n");
      out.write(".searchholder{padding-left: 20px;}\r\n");
      out.write("#list{height: auto; padding: 10px; }\r\n");
      out.write(".searchbutton{margin-top:2%; width:200px; height:80%; background-color: #F0F2F5; border-radius: 50px;}\r\n");
      out.write(".searchicon{padding-top:6%;padding-left:5%; margin-left:3%;}\r\n");
      out.write(".navname{left:0px; padding-top: 20px; margin:0px;}\r\n");
      out.write(".navname1{left:0px; padding-top: 6px; margin:0px;}\r\n");
      out.write(".divmiddlebox{padding-left: 10px; margin:0px;}\r\n");
      out.write(".divrightbox{margin:0px; padding-top: 10px; display:flex;}\r\n");
      out.write(".profile{border-radius: 30px;}\r\n");
      out.write(".ipbox{display: flex;  width:50%; margin-top:20px; flex-flow: row wrap;}\r\n");
      out.write(".eachip{width:33%; flex-grow: 3; padding: 0px; border-radius: 50px;}\r\n");
      out.write("#ipdiv{position:absolute; padding-top:50px; padding:0px; visibility:hidden; top:35%; left:45%; width:auto; height:auto; background-color:white; border: 1px solid #E2E4E7;}\r\n");
      out.write(".mainbox{display: flex; margin-top:100px;}\r\n");
      out.write("#searchbar{padding-left:5px; position:absolute; visibility:hidden; width:18%; background-color: white; box-shadow: rgba(0, 0, 0, 0.15) 1.95px 1.95px 2.6px;}\r\n");
      out.write("\r\n");
      out.write(".newmember{\r\n");
      out.write("background-color:MediumSeaGreen;\r\n");
      out.write("border:none;\r\n");
      out.write("color:white;\r\n");
      out.write("border-radius:3px;\r\n");
      out.write("height:35px;\r\n");
      out.write("width:150px;\r\n");
      out.write("margin-top:7px;\r\n");
      out.write("}\r\n");
      out.write(".newmember:hover{\r\n");
      out.write("background-color:seagreen;\r\n");
      out.write("}\r\n");
      out.write(".lgb{\r\n");
      out.write("background-color:dodgerblue;\r\n");
      out.write("border:none;\r\n");
      out.write("color:white;\r\n");
      out.write("border-radius:3px;\r\n");
      out.write("margin:3px;\r\n");
      out.write("font-size:17px;\r\n");
      out.write("width:70px;\r\n");
      out.write("height:27px;\r\n");
      out.write("margin-top:10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>\r\n");
      out.write("\r\n");
      out.write("AceBook\r\n");
      out.write("</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"nav\">\r\n");
      out.write("\t<div id=\"searchbar\">\r\n");
      out.write("\t<i onclick=\"closesearch()\" class=\"fa fa-arrow-left fa-2x pointer\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t<input type=\"text\" id=\"search\" placeholder=\"유저검색\"/>\r\n");
      out.write("\t<div id=\"list\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<div class=\"divbar\">\r\n");
 if(session!=null){
      out.write("\r\n");
      out.write("<div class=\"divbarleft\">\r\n");
      out.write("<img class=\"pointer\" onclick=\"main(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.sn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\" src =\"/resources/img/acebooklogo.png\"  height=\"50\" width=\"50\"/>\r\n");
      out.write("<div class=\"pointer searchbutton\" ><i class=\"fa fa-search fa-1x searchicon\" aria-hidden=\"true\"><a class=\"searchholder\"><b>Acebook 검색</b></a></i>\r\n");
      out.write("</div>\r\n");
      out.write("<a class=\"navname\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 접속 환영합니다.</a> \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"divbarmiddle\">\r\n");
      out.write("<div class=\"divbarindex pointer barindexbottom\" id=\"index1\" onclick=\"main(");
      out.print(session.getAttribute("sn"));
      out.write(")\"><i class=\"fa fa-home  fa-2x \" aria-hidden=\"true\" ></i></div>\r\n");
      out.write("<div class=\"divbarindex pointer\" id=\"index2\" onclick=\"friend(");
      out.print(session.getAttribute("sn"));
      out.write(")\"><i class=\"fa fa-users  fa-2x\" aria-hidden=\"true\" ></i></div>\r\n");
      out.write("<div class=\"divbarindex pointer\" id=\"index3\" onclick=\"person(");
      out.print(session.getAttribute("sn"));
      out.write(")\"><i class=\"fa fa-user  fa-2x\" aria-hidden=\"true\" ></i></div>\r\n");
      out.write("</div>\r\n");
} else {
      out.write(" \r\n");
      out.write("<form onsubmit=\"로그인()\" action=\"main\" method=\"post\">id <input type=\"text\" name=\"id\" id=\"id\" /> password <input type=\"password\" name=\"password\" id=\"password\" /><input type=\"submit\" class=\"lgb\" value=\"로그인\" /></form>\r\n");
      out.write("<button onclick=\"open_layer(1,0)\" class=\"newmember\">새 계정 만들기</button>\r\n");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"divbarright\">\r\n");
 if(session!=null){
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"divrightbox pointer\" onclick=\"person(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.sn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\"><img class=\" profile\" src =\"/board/attach/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.profile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  height=\"30\" width=\"30\"/><a class=\"navname1\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></a></div>\r\n");
      out.write("<div class=\"divrightbox pointer\"><button onclick=\"location.href='/logout'\">로그아웃</button></div>\r\n");
}
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /WEB-INF/views/acebook.jsp(187,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test eq true}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("<div id=\"con\">\r\n");
            out.write("<div id=\"left\">\r\n");
            out.write("<iframe src=\"/testplus\" name=\"lframe\" onload=\"Height();\" frameborder=\"0\" scrolling=\"no\" style=\"overflow-x:hidden; overflow:auto; width:100%; height:100%;\"></iframe>\r\n");
            out.write("</div>\r\n");
            out.write("<div id=\"middle\">\r\n");
            out.write("<iframe src=\"/mainboard/");
            out.print(session.getAttribute("sn"));
            out.write("\" name=\"mframe\" onload=\"Height();\" frameborder=\"0\" style=\"overflow-x:hidden; overflow:auto; width:100%; height:100%;\"></iframe>\r\n");
            out.write("</div>\r\n");
            out.write("<div id=\"right\">\r\n");
            out.write("<iframe src=\"/friendstate\" name=\"rframe\" onload=\"Height();\" frameborder=\"0\" style=\"overflow-x:hidden; overflow:auto; width:100%; height:100%;\"></iframe>\r\n");
            out.write("</div>\r\n");
            out.write("\r\n");
            out.write("</div>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"ipdiv\">\r\n");
      out.write("   <form action=\"main\" method=\"post\">\r\n");
      out.write("   <input type=\"hidden\" name=\"id\" id=\"ipid\"/> \r\n");
      out.write("   <img class=\" profile\"  id=\"ipprofile\" height=\"150\" width=\"200\"/><br>\r\n");
      out.write("   <input type=\"text\" id=\"ipname\" readonly=\"readonly\" /><br>\r\n");
      out.write("   <input type=\"password\" id=\"ippassword\" name=\"password\" placeholder=\"비밀번호입력\"/><br>\r\n");
      out.write("   <input type=\"submit\" value=\"로그인\" /><button type=\"button\" onclick=\"closeiplogin()\">취소</button>\r\n");
      out.write("   </form>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"divpop\" style=\"position:absolute; top:100px;; left:400px; z-index:300; visibility:hidden;\">\r\n");
      out.write("<table cellpadding=\"5\" cellspacing=\"0\" bgcolor=\"lightgrey\" border=\"1px;\" bordercolor=\"lightgrey\">\r\n");
      out.write("<tr><td>\r\n");
      out.write("<iframe name=\"i_frame\" src=\"#\" width=\"600px\" height=\"700px\" marginwidth=\"0\" marginheight=\"0\" frameborder=\"no\" scrolling=\"auto\"></iframe>\r\n");
      out.write("</td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"right\" height=\"1px;\" bgcolor=\"lightgrey\">\r\n");
      out.write("<button type=\"button\" class=\"button2\" onclick=\"close_layer();\">취소</button>\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" id=\"msg\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!-- javaScript -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function open_layer(key,board){\r\n");
      out.write("\tif(key==1){ var page = \"/member\";}\r\n");
      out.write("\tif(key==2){ var page = \"/openinputadd/\"+board;}\r\n");
      out.write("\tdocument.all['divpop'].style.visibility = \"visible\";\r\n");
      out.write("\tdocument.i_frame.location.replace(page);\r\n");
      out.write("\t}\r\n");
      out.write("function close_layer(){\r\n");
      out.write("\t document.all['divpop'].style.visibility = \"hidden\";\r\n");
      out.write("\t}\r\n");
      out.write("function closelayer(){\r\n");
      out.write("\t document.all['divpop'].style.visibility = \"hidden\";\r\n");
      out.write("}\r\n");
      out.write("function 로그인(){\r\n");
      out.write("var id = document.querySelector(\"#id\");\r\n");
      out.write("if(id.value==\"\"){\r\n");
      out.write("\talert(\"아이디가 입력되지 않앗어요!\");\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("var password = document.querySelector(\"#password\");\r\n");
      out.write("if(password.value==\"\"){\r\n");
      out.write("\talert(\"비밀번호가 입력되지 않앗어요!\");\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("return true;\r\n");
      out.write("}\r\n");
      out.write("function iplogin(id,name,profile){\r\n");
      out.write("\tdocument.all['ipdiv'].style.visibility = \"visible\";\r\n");
      out.write("\t$('#ipid').val(id);\r\n");
      out.write("\t$('#ipname').val(name);\r\n");
      out.write("\t$(\"#ippassword\").focus();\r\n");
      out.write("\tjQuery('#ipprofile').attr(\"src\",\"board/attach/\"+profile);\r\n");
      out.write("}\r\n");
      out.write("function iplogdelete(sn){\r\n");
      out.write("\tlocation.href=\"/iplogdelete/\"+sn;\r\n");
      out.write("}\r\n");
      out.write("function closeiplogin(){\r\n");
      out.write("\t$('#ippassword').val(\"\");\r\n");
      out.write("\tdocument.all['ipdiv'].style.visibility = \"hidden\";\r\n");
      out.write("}\r\n");
      out.write("function person(sn){\r\n");
      out.write("\tdocument.mframe.location.replace(\"/personpage/\"+sn);\r\n");
      out.write("\t$('#left').attr('id', 'zero1');\r\n");
      out.write("\t$('#right').attr('id', 'zero2');\r\n");
      out.write("\t$('iframe[name=rframe]').hide();\r\n");
      out.write("\t$('iframe[name=lframe]').hide();\r\n");
      out.write("\t$('#index1').attr('class', 'divbarindex pointer');\r\n");
      out.write("\t$('#index2').attr('class', 'divbarindex pointer');\r\n");
      out.write("\t$('#index3').attr('class', 'divbarindex pointer barindexbottom');\r\n");
      out.write("}\r\n");
      out.write("function main(sn){\r\n");
      out.write("\tdocument.lframe.location.replace(\"/testplus\");\r\n");
      out.write("\tdocument.mframe.location.replace(\"/mainboard/\"+sn);\r\n");
      out.write("\t$('#zero1').attr('id', 'left');\r\n");
      out.write("\t$('#zero2').attr('id', 'right');\r\n");
      out.write("\t$('#index1').attr('class', 'divbarindex pointer barindexbottom');\r\n");
      out.write("\t$('#index2').attr('class', 'divbarindex pointer ');\r\n");
      out.write("\t$('#index3').attr('class', 'divbarindex pointer');\r\n");
      out.write("\t$('iframe[name=rframe]').show();\r\n");
      out.write("\t$('iframe[name=lframe]').show();\r\n");
      out.write("}\r\n");
      out.write("function friend(sn){\r\n");
      out.write("\tdocument.mframe.location.replace(\"/friend\");\r\n");
      out.write("\t$('#left').attr('id', 'zero1');\r\n");
      out.write("\t$('#right').attr('id', 'zero2');\r\n");
      out.write("\t$('iframe[name=rframe]').hide();\r\n");
      out.write("\t$('iframe[name=lframe]').hide();\r\n");
      out.write("\t$('#index1').attr('class', 'divbarindex pointer');\r\n");
      out.write("\t$('#index2').attr('class', 'divbarindex pointer barindexbottom');\r\n");
      out.write("\t$('#index3').attr('class', 'divbarindex pointer');\r\n");
      out.write("}\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t   var outHtml = '';\r\n");
      out.write("\t    $('#search').keyup(function(){//무한검색\r\n");
      out.write("\t        if ( $('#search').val().length > 0) {//length 로 글자수 지정해주기\r\n");
      out.write("\t            var search = $(this).val();\r\n");
      out.write("\t        \r\n");
      out.write("\t            // ajax 실행\r\n");
      out.write("\t            $.ajax({ \r\n");
      out.write("\t                type : 'POST',\r\n");
      out.write("\t                url : '/selectuser',\r\n");
      out.write("\t                data:{name: search},\r\n");
      out.write("\t                success : function(data) { \r\n");
      out.write("\t                   $(\"#list\").empty();\r\n");
      out.write("\t                   $.each(data,function(index, item){\r\n");
      out.write("\t                      $(\"#list\").append('<div class=\"pointer\" onclick = \"search('+item.sn+')\">'+'<img class=\"profile\" src=\"/board/attach/'+item.profile+'\" height=\"30\" width=\"30\"/>'+item.name+'</div>');\r\n");
      out.write("\t                      /*alert(item.name);*/ });\r\n");
      out.write("\t                },\r\n");
      out.write("\t                 errer : function(data){\r\n");
      out.write("\t                \tconsole.log('SelectUserError');\r\n");
      out.write("\t                } \r\n");
      out.write("\t            }); // end ajax\r\n");
      out.write("\t        }\r\n");
      out.write("\t    }); // end keyup\r\n");
      out.write("\t}); \t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("//아이프레임\r\n");
      out.write("function calcHeight() {\r\n");
      out.write("\t\tvar the_height = document.getElementsByName('iframe').contentWindow. document.body.scrollHeight;\r\n");
      out.write("\t\tdocument.getElementById('iframe').height = the_height; \r\n");
      out.write("\t\tdocument.getElementById('iframe').style.overflow = \"hidden\"; }\r\n");
      out.write("\t\r\n");
      out.write("$(\".searchbutton\").on('click', function(event){\r\n");
      out.write("\tdocument.all['searchbar'].style.visibility = \"visible\";\r\n");
      out.write("\t$(\"#search\").focus();\r\n");
      out.write("});\r\n");
      out.write("function search(sn){\r\n");
      out.write("\tperson(sn);\r\n");
      out.write("\tclosesearch();\r\n");
      out.write("}\r\n");
      out.write("function closesearch(){\r\n");
      out.write("\tdocument.all['searchbar'].style.visibility = \"hidden\";\r\n");
      out.write("\t$('#list').empty();\r\n");
      out.write("\t$('#search').val(\"\");\r\n");
      out.write("}\r\n");
      out.write("window.onload = function(){\r\n");
      out.write("\tif($('#msg').val() !=\"\"){alert($('#msg').val());}\r\n");
      out.write("\t}\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/acebook.jsp(203,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty members}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("   <div>\r\n");
          out.write("    <div class=\"mainbox\"><b>최근로그인기록</b></div>\r\n");
          out.write("  \t<div class=\"ipbox\">\r\n");
          out.write("      ");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write(" \t </div>\r\n");
          out.write(" \t</div>\r\n");
          out.write("   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/acebook.jsp(207,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("member");
      // /WEB-INF/views/acebook.jsp(207,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/acebook.jsp(207,6) '${members}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${members}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t<div class=\"eachip pointer\" onclick=\"iplogin('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.profile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\">\r\n");
            out.write("\t\t<img src =\"/board/attach/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.profile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" height=\"200\" width=\"200\"/><br>\r\n");
            out.write("\t\t<a><b>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</b></a><button type=\"button\" onclick=\"iplogdelete(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.sn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\">삭제</button>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
